
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: michaelpmartin
  password:

development:
  <<: *default
  host: localhost
  database: myflix_development

test:
  <<: *default
  database: myflix_test
