
Video.create([
  { title: 'Bugs Bunny, A Cartoon Revue',
    description: 'A Feature Length Laugh Riot Featuring Many of Warner Bros. Famous Cartoon Stars',
    poster_small_url: 'bugs-bunny-a-cartoon-revue-1953.jpg',
    poster_large_url: '',
    created_at: 61.years.ago },
  { title: 'Casablanca',
    description: 'In World War II Casablanca, Rick Blaine, exiled American and former freedom fighter, runs the most popular nightspot in town. The cynical lone wolf Blaine comes into the possession of two valuable letters of transit. When Nazi Major Strasser arrives in Casablanca, the sycophantic police Captain Renault does what he can to please him, including detaining a Czechoslovak underground leader Victor Laszlo. Much to Rick\'s surprise, Lazslo arrives with Ilsa, Rick\'s one time love. Rick is very bitter towards Ilsa, who ran out on him in Paris, but when he learns she had good reason to, they plan to run off together again using the letters of transit. Well, that was their original plan....',
    poster_small_url: 'casablanca-1942.jpg',
    poster_large_url: '',
    created_at: 72.years.ago },
  { title: 'Gone with the Wind',
    description: 'Scarlett is a woman who can deal with a nation at war, Atlanta burning, the Union Army carrying off everything from her beloved Tara, the carpetbaggers who arrive after the war. Scarlett is beautiful. She has vitality. But Ashley, the man she has wanted for so long, is going to marry his placid cousin, Melanie. Mammy warns Scarlett to behave herself at the party at Twelve Oaks. There is a new man there that day, the day the Civil War begins. Rhett Butler. Scarlett does not know he is in the room when she pleads with Ashley to choose her instead of Melanie.',
    poster_small_url: 'gone-with-the-wind-1939.jpg',
    poster_large_url: '',
    created_at: 72.years.ago },
  { title: 'It Happened At the World\'s Fair',
    description: 'Mike and Danny fly a crop duster, but because of Danny\'s gambling debts, a local sheriff seizes it. Trying to earn money, they hitch-hike to the World\'s Fair in Seattle. While Danny tries to earn money playing poker, Mike takes care of a small girl, Sue-Lin, whose Uncle Walter has disappeared. Being a ladies\' man, he also finds the time to court a young nurse, Diane.',
    poster_small_url: 'it-happened-at-the-world-s-fair-1963.jpg',
    poster_large_url: '',
    created_at: 51.years.ago },
  { title: 'King Kong',
    description: 'Carl Denham needs to finish his movie and has the perfect location; Skull Island. But he still needs to find a leading lady. This \'soon-to-be-unfortunate\' soul is Ann Darrow. No one knows what they will encounter on this island and why it is so mysterious, but once they reach it, they will soon find out. Living on this hidden island is a giant gorilla and this beast now has Ann is it\'s grasps. Carl and Ann\'s new love, Jack Driscoll must travel through the jungle looking for Kong and Ann, whilst avoiding all sorts of creatures and beasts.',
    poster_small_url: 'king-kong-1933.jpg',
    poster_large_url: '',
    created_at: 81.years.ago },
  { title: 'Metropolis',
    description: 'Sometime in the future, the city of Metropolis is home to a Utopian society where its wealthy residents live a carefree life. One of those is Freder Fredersen. One day, he spots a beautiful woman with a group of children, she and the children who quickly disappear. Trying to follow her, he, oblivious to such, is horrified to find an underground world of workers, apparently who run the machinery which keeps the above ground Utopian world functioning. One of the few people above ground who knows about the world below is Freder\'s father, Joh Fredersen, who is the founder and master of Metropolis. Freder learns that the woman is Maria, who espouses the need to join the "hands" - the workers - to the "head" - those in power above - by a mediator or the "heart". Freder wants to help the plight of the workers in the want for a better life. But when Joh learns of what Maria is espousing and that Freder is joining their cause, Joh, with the assistance of an old colleague and now nemesis named ...',
    poster_small_url: 'metropolis-1927.jpg',
    poster_large_url: '',
    created_at: 87.years.ago },
  { title: 'Shall We Dance',
    description: 'Ballet star Pete "Petrov" Peters arranges to cross the Atlantic aboard the same ship as the dancer he\'s fallen for but barely knows, musical star Linda Keene. By the time the ocean liner reaches New York, a little white lie has churned through the rumor mill and turned into a hot gossip item: that the two celebrities are secretly married.',
    poster_small_url: 'shall-we-dance-1937.jpg',
    poster_large_url: '',
    created_at: 77.years.ago },
  { title: 'Steamboat Willie',
    description: 'Mickey is piloting a steamboat when Captain Pete comes to the bridge and throws him off. They stop to pick up cargo. Minnie just misses the boat and Mickey uses the crane to grab her. She drops her sheet music of "Turkey in the Straw" and a goat eats it. With help from Mickey, she cranks the goat\'s tail, and it plays the tune. Mickey accompanies on percussion and by torturing various animals, until Pete comes down and puts a stop to it, putting Mickey to work peeling potatoes. While this is the first sound Mickey Mouse, there\'s no dialog.',
    poster_small_url: 'steamboat-willie-1928.jpg',
    poster_large_url: '',
    created_at: 86.years.ago },
  { title: 'The Wizard of Oz',
    description: 'In this charming film based on the popular L. Frank Baum stories, Dorothy and her dog Toto are caught in a tornado\'s path and somehow end up in the land of Oz. Here she meets some memorable friends and foes in her journey to meet the Wizard of Oz who everyone says can help her return home and possibly grant her new friends their goals of a brain, heart and courage.',
    poster_small_url: 'the-wizard-of-oz-1939.jpg',
    poster_large_url: '',
    created_at: 75.years.ago },
  { title: 'Brave',
    description: 'Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.',
    poster_small_url: 'brave-2012.jpg',
    poster_large_url: '',
    created_at: 2.years.ago },
  { title: 'Bullitt',
    description: 'An all guts, no glory San Francisco cop becomes determined to find the underworld kingpin that killed the witness in his protection.',
    poster_small_url: 'bullitt-1968.jpg',
    poster_large_url: '',
    created_at: 46.years.ago },
  { title: 'Caddyshack',
    description: 'An exclusive golf course has to deal with a brash new member and a destructive dancing gopher.',
    poster_small_url: 'caddyshack-1980.jpg',
    poster_large_url: '',
    created_at: 34.years.ago },
  { title: 'Captain America: The First Avenger',
    description: 'After being deemed unfit for military service, Steve Rogers volunteers for a top secret research project that turns him into Captain America, a superhero dedicated to defending USA ideals.',
    poster_small_url: 'captain-america-2011.jpg',
    poster_large_url: '',
    created_at: 3.years.ago },
  { title: 'Captain America: The Winter Soldier',
    description: 'Steve Rogers struggles to embrace his role in the modern world and battles a new threat from old history: the Soviet agent known as the Winter Soldier.',
    poster_small_url: 'captain-america-2-2014.jpg',
    poster_large_url: '',
    created_at: 1.year.ago },
  { title: 'Casino Royale',
    description: 'Armed with a licence to kill, Secret Agent James Bond sets out on his first mission as 007 and must defeat a weapons dealer in a high stakes game of poker at Casino Royale, but things are not what they seem.',
    poster_small_url: 'casino-royale-2006.jpg',
    poster_large_url: '',
    created_at: 8.years.ago },
  { title: 'Despicable Me 2',
    description: 'Gru is recruited by the Anti-Villain League to help deal with a powerful new super criminal.',
    poster_small_url: 'despicable-me-2-2013.jpg',
    poster_large_url: '',
    created_at: 1.year.ago },
  { title: 'Ferris Bueller\'s Day Off',
    description: 'A high school wise guy is determined to have a day off from school, despite of what the principal thinks of that.',
    poster_small_url: 'ferris-bueller-s-day-off-1986.jpg',
    poster_large_url: '',
    created_at: 28.years.ago },
  { title: 'Kill Bill Volume 1',
    description: 'The Bride wakens from a four-year coma. The child she carried in her womb is gone. Now she must wreak vengeance on the team of assassins who betrayed her - a team she was once part of.',
    poster_small_url: 'kill-bill-vol-1-2003.jpg',
    poster_large_url: '',
    created_at: 11.years.ago },
  { title: 'Monty Python and the Holy Grail',
    description: 'King Arthur and his knights embark on a low-budget search for the Grail, encountering many very silly obstacles.',
    poster_small_url: 'monty-python-and-the-holy-grail-1975.jpg',
    poster_large_url: '',
    created_at: 39.years.ago },
  { title: 'Peter Pan',
    description: 'Wendy and her brothers are whisked away to the magical world of Neverland with the hero of their stories, Peter Pan.',
    poster_small_url: 'peter-pan-1953.jpg',
    poster_large_url: '',
    created_at: 61.years.ago },
  { title: 'Pinocchio',
    description: 'A living puppet, with the help of a cricket as his conscience, must prove himself worthy to become a real boy.',
    poster_small_url: 'pinocchio-1940.jpg',
    poster_large_url: '',
    created_at: 74.years.ago },
  { title: 'Sabrina',
    description: 'A playboy becomes interested in the daughter of his family\'s chauffeur. But it\'s his more serious brother who would be the better man for her.',
    poster_small_url: 'sabrina-1954.jpg',
    poster_large_url: '',
    created_at: 60.years.ago },
  { title: 'Skyfall',
    description: 'Bond\'s loyalty to M is tested when her past comes back to haunt her. Whilst MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.',
    poster_small_url: 'skyfall-2012.jpg',
    poster_large_url: '',
    created_at: 2.years.ago },
  { title: 'The Goonies',
    description: 'A group of kids set out on an adventure in search of pirate treasure that could save their homes from foreclosure.',
    poster_small_url: 'the-goonies-1985.jpg',
    poster_large_url: '',
    created_at: 29.years.ago },
  { title: 'The Hangover',
    description: 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.',
    poster_small_url: 'the-hangover-2009.jpg',
    poster_large_url: '',
    created_at: 6.years.ago },
  { title: 'The Lego Movie',
    description: 'An ordinary Lego construction worker, thought to be the prophesied \'Special\', is recruited to join a quest to stop an evil tyrant from gluing the Lego universe into eternal stasis.',
    poster_small_url: 'the-lego-movie-2014.jpg',
    poster_large_url: '',
    created_at: 1.year.ago },
  { title: 'The Pink Panther',
    description: 'Bumbling and conceited French police inspector Clouseau tries to catch The Phantom, a daring jewel thief whose identity and features are unknown - and is acting right under his nose.',
    poster_small_url: 'the-pink-panther-1963.jpg',
    poster_large_url: '',
    created_at: 51.years.ago },
  { title: 'Thunderball',
    description: 'James Bond heads to The Bahamas to recover two nuclear warheads stolen by SPECTRE agent Emilio Largo in an international extortion scheme.',
    poster_small_url: 'thunderball-1965.jpg',
    poster_large_url: '',
    created_at: 49.years.ago },
  { title: 'Toy Story 3',
    description: 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.',
    poster_small_url: 'toy-story-3-2010.jpg',
    poster_large_url: '',
    created_at: 4.years.ago },
  { title: 'You Only Live Twice',
    description: 'Agent 007 and the Japanese secret service ninja force must find and stop the true culprit of a series of spacejackings before nuclear war is provoked.',
    poster_small_url: 'you-only-live-twice-1967.jpg',
    poster_large_url: '',
    created_at: 47.years.ago }
])

Category.create([
  { name: 'Action & Adventure' },
  { name: 'Anime' },
  { name: 'Children & Family' },
  { name: 'Classics' },
  { name: 'Comedies' },
  { name: 'Cult Movies' },
  { name: 'Documentaries' },
  { name: 'Dramas' },
  { name: 'Faith & Spirituality' },
  { name: 'Foreign' },
  { name: 'Gay & Lesbian' },
  { name: 'Horror' },
  { name: 'Independent' },
  { name: 'Music' },
  { name: 'Musicals' },
  { name: 'Romance' },
  { name: 'Sci-Fi & Fantasy' },
  { name: 'Sports Movies' },
  { name: 'Thrillers' },
  { name: 'TV Shows' }
])

VideoCategory.create([
  { video_id: 1, category_id: 4 },
  { video_id: 2, category_id: 4 },
  { video_id: 3, category_id: 4 },
  { video_id: 4, category_id: 4 },
  { video_id: 5, category_id: 4 },
  { video_id: 6, category_id: 4 },
  { video_id: 7, category_id: 4 },
  { video_id: 8, category_id: 4 },
  { video_id: 9, category_id: 4 },
  { video_id: 1, category_id: 5 },
  { video_id: 2, category_id: 8 },
  { video_id: 3, category_id: 8 },
  { video_id: 4, category_id: 5 },
  { video_id: 5, category_id: 8 },
  { video_id: 6, category_id: 8 },
  { video_id: 7, category_id: 15 },
  { video_id: 8, category_id: 5 },
  { video_id: 9, category_id: 8 },
  { video_id: 10, category_id: 3 },
  { video_id: 10, category_id: 4 },
  { video_id: 11, category_id: 1 },
  { video_id: 11, category_id: 4 },
  { video_id: 11, category_id: 19 },
  { video_id: 12, category_id: 4 },
  { video_id: 12, category_id: 5 },
  { video_id: 13, category_id: 1 },
  { video_id: 14, category_id: 1 },
  { video_id: 15, category_id: 1 },
  { video_id: 15, category_id: 19 },
  { video_id: 16, category_id: 3 },
  { video_id: 16, category_id: 5 },
  { video_id: 17, category_id: 4 },
  { video_id: 17, category_id: 5 },
  { video_id: 18, category_id: 1 },
  { video_id: 19, category_id: 4 },
  { video_id: 19, category_id: 5 },
  { video_id: 20, category_id: 3 },
  { video_id: 20, category_id: 4 },
  { video_id: 21, category_id: 3 },
  { video_id: 21, category_id: 4 },
  { video_id: 22, category_id: 4 },
  { video_id: 22, category_id: 8 },
  { video_id: 23, category_id: 1 },
  { video_id: 23, category_id: 19 },
  { video_id: 24, category_id: 3 },
  { video_id: 24, category_id: 4 },
  { video_id: 25, category_id: 5 },
  { video_id: 26, category_id: 3 },
  { video_id: 26, category_id: 5 },
  { video_id: 27, category_id: 4 },
  { video_id: 27, category_id: 5 },
  { video_id: 28, category_id: 1 },
  { video_id: 28, category_id: 4 },
  { video_id: 28, category_id: 19 },
  { video_id: 29, category_id: 3 },
  { video_id: 30, category_id: 1 },
  { video_id: 30, category_id: 4 },
  { video_id: 30, category_id: 19 }
])

Fabricate.times(25, :user)

User.all.each do |user|

  Video.all.each do |video|

    Fabricate(:review, user_id: user.id, video_id: video.id)
  end

  3.times do
    Fabricate(:queue_item, user_id: user.id, video_id: (1..30).to_a.sample, list_order: Fabricate.sequence(1))
  end
end

User.all.each do |leader|

  User.all.each do |follower|

    Fabricate(:relationship, leader_id: leader.id, follower_id: follower.id) unless leader.id == follower.id
  end
end

