

VideoCategory.create([
  { video_id: 1, category_id: 4 },
  { video_id: 2, category_id: 4 },
  { video_id: 3, category_id: 4 },
  { video_id: 4, category_id: 4 },
  { video_id: 5, category_id: 4 },
  { video_id: 6, category_id: 4 },
  { video_id: 7, category_id: 4 },
  { video_id: 8, category_id: 4 },
  { video_id: 9, category_id: 4 },

  { video_id: 1, category_id: 5 },
  { video_id: 2, category_id: 8 },
  { video_id: 3, category_id: 8 },
  { video_id: 4, category_id: 5 },
  { video_id: 5, category_id: 8 },
  { video_id: 6, category_id: 8 },
  { video_id: 7, category_id: 15 },
  { video_id: 8, category_id: 5 },
  { video_id: 9, category_id: 8 },

  { video_id: 10, category_id: 3 },
  { video_id: 10, category_id: 4 },
  { video_id: 11, category_id: 1 },
  { video_id: 11, category_id: 4 },
  { video_id: 11, category_id: 19 },
  { video_id: 12, category_id: 4 },
  { video_id: 12, category_id: 5 },
  { video_id: 13, category_id: 1 },
  { video_id: 14, category_id: 1 },
  { video_id: 15, category_id: 1 },
  { video_id: 15, category_id: 19 },
  { video_id: 16, category_id: 3 },
  { video_id: 16, category_id: 5 },

  { video_id: 17, category_id: 4 },
  { video_id: 17, category_id: 5 },
  { video_id: 18, category_id: 1 },
  { video_id: 19, category_id: 4 },
  { video_id: 19, category_id: 5 },
  { video_id: 20, category_id: 3 },
  { video_id: 20, category_id: 4 },
  { video_id: 21, category_id: 3 },
  { video_id: 21, category_id: 4 },
  { video_id: 22, category_id: 4 },
  { video_id: 22, category_id: 8 },
  { video_id: 23, category_id: 1 },
  { video_id: 23, category_id: 19 },

  { video_id: 24, category_id: 3 },
  { video_id: 24, category_id: 4 },
  { video_id: 25, category_id: 5 },
  { video_id: 26, category_id: 3 },
  { video_id: 26, category_id: 5 },
  { video_id: 27, category_id: 4 },
  { video_id: 27, category_id: 5 },
  { video_id: 28, category_id: 1 },
  { video_id: 28, category_id: 4 },
  { video_id: 28, category_id: 19 },
  { video_id: 29, category_id: 3 },
  { video_id: 30, category_id: 1 },
  { video_id: 30, category_id: 4 },
  { video_id: 30, category_id: 19 }
])
